# no.sort

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np

In [2]:
a =np.random.randint(1,100,25)
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[91, 67, 98, 94],
       [94, 95, 81, 79],
       [50, 39, 42, 37],
       [88, 18, 87, 27],
       [79, 25, 73, 88],
       [ 1, 11, 70, 63]])

In [4]:
np.sort(a)

# sorting array in ascending order

array([ 3,  4,  9, 15, 20, 20, 30, 30, 33, 34, 44, 49, 52, 54, 57, 62, 70,
       71, 72, 80, 82, 84, 86, 90, 99])

In [5]:
np.sort(b)

# row wise sorting

array([[67, 91, 94, 98],
       [79, 81, 94, 95],
       [37, 39, 42, 50],
       [18, 27, 87, 88],
       [25, 73, 79, 88],
       [ 1, 11, 63, 70]])

In [6]:
# for column wise sorting we use axis = 0
np.sort(b, axis=0)

array([[ 1, 11, 42, 27],
       [50, 18, 70, 37],
       [79, 25, 73, 63],
       [88, 39, 81, 79],
       [91, 67, 87, 88],
       [94, 95, 98, 94]])

In [7]:
# If we want to sort it into reverse order
np.sort(b)[::-1]

array([[ 1, 11, 63, 70],
       [25, 73, 79, 88],
       [18, 27, 87, 88],
       [37, 39, 42, 50],
       [79, 81, 94, 95],
       [67, 91, 94, 98]])

In [8]:
# If we want to sort it into reverse order
np.sort(a)[::-1]

array([99, 90, 86, 84, 82, 80, 72, 71, 70, 62, 57, 54, 52, 49, 44, 34, 33,
       30, 30, 20, 20, 15,  9,  4,  3])

#np.append
- The numpy.append() appends values along the mentioned axis at the end of the array

In [9]:
np.append(a,200)

array([ 82,  30,  49,  71,  99,   3,  70,   9,  72,  80,  20,  84,  62,
        86,  52,  20,   4,  57,  15,  34,  30,  90,  33,  44,  54, 200])

In [10]:
# appending with 2D array
# append a column with all element 1
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[91., 67., 98., 94.,  1.],
       [94., 95., 81., 79.,  1.],
       [50., 39., 42., 37.,  1.],
       [88., 18., 87., 27.,  1.],
       [79., 25., 73., 88.,  1.],
       [ 1., 11., 70., 63.,  1.]])

#Concatenate

- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [11]:
c = np.arange(6).reshape(3,2)
d = np.arange(6,12).reshape(3,2)
print(c)
print(d)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [12]:
np.concatenate((c,d))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [13]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

#np.unique
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
e = np.array([1,2,3,4,5,4,3,2,1,2,4])
len(e)

11

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5])

#np.expand_dims
- With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [17]:
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [18]:
# making a new dimension of array with axis = 0
np.expand_dims(a,axis = 0)

array([[82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,
         4, 57, 15, 34, 30, 90, 33, 44, 54]])

In [19]:
np.shape(np.expand_dims(a,axis = 0))

(1, 25)

In [20]:
# making a new dimension of array with axis = 1
np.expand_dims(a,axis = 1)

array([[82],
       [30],
       [49],
       [71],
       [99],
       [ 3],
       [70],
       [ 9],
       [72],
       [80],
       [20],
       [84],
       [62],
       [86],
       [52],
       [20],
       [ 4],
       [57],
       [15],
       [34],
       [30],
       [90],
       [33],
       [44],
       [54]])

In [21]:
# Finding the shape
np.expand_dims(a,axis = 1).shape

(25, 1)

In [22]:
# Finding the shape in my way
np.shape(np.expand_dims(a,axis = 1))

(25, 1)

#np.where
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [23]:
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [24]:
np.where(a>55)

# It gives the index values

(array([ 0,  3,  4,  6,  8,  9, 11, 12, 13, 17, 21]),)

In [25]:
# Replace all values > 50 with 0
# How the function works
#np.where (array name(a) condition(</>/=)true(if true then use (something like any number which you want)false(if false then use what you want)))
np.where(a>50,0,a)

array([ 0, 30, 49,  0,  0,  3,  0,  9,  0,  0, 20,  0,  0,  0,  0, 20,  4,
        0, 15, 34, 30,  0, 33, 44,  0])

In [26]:
# Replace all values > 50 with 0
# How the function works
#np.where (array name(a) condition(</>/=)true(if true then use (something like any number which you want)false(if false then use what you want)))
np.where(a>50,"z",a)

array(['z', '30', '49', 'z', 'z', '3', 'z', '9', 'z', 'z', '20', 'z', 'z',
       'z', 'z', '20', '4', 'z', '15', '34', '30', 'z', '33', '44', 'z'],
      dtype='<U21')

In [27]:
# Replace all the even numbers with 1

np.where(a%2 == 0,1,a)

array([ 1,  1, 49, 71, 99,  3,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       57, 15,  1,  1,  1, 33,  1,  1])

#np.argmax
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [28]:
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [29]:
np.argmax(a)

4

In [30]:
# To check in 2D
b

array([[91, 67, 98, 94],
       [94, 95, 81, 79],
       [50, 39, 42, 37],
       [88, 18, 87, 27],
       [79, 25, 73, 88],
       [ 1, 11, 70, 63]])

In [31]:
np.argmax(b, axis=1)
# Here it gives our element row wise

array([2, 1, 0, 0, 3, 2])

In [32]:
np.argmax(b, axis=0)
# Here it gives our element column wise

array([1, 1, 0, 0])

In [33]:
# np.argmin
# It gives minimun number's index number in the array

a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [34]:
np.argmin(a)

5

#np.cumsum
- numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [35]:
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [36]:
np.cumsum(a)

array([  82,  112,  161,  232,  331,  334,  404,  413,  485,  565,  585,
        669,  731,  817,  869,  889,  893,  950,  965,  999, 1029, 1119,
       1152, 1196, 1250])

In [37]:
b

array([[91, 67, 98, 94],
       [94, 95, 81, 79],
       [50, 39, 42, 37],
       [88, 18, 87, 27],
       [79, 25, 73, 88],
       [ 1, 11, 70, 63]])

In [38]:
np.cumsum(b)
# It converts theis 2D array into 1D and then gives us the cummulative sum

array([  91,  158,  256,  350,  444,  539,  620,  699,  749,  788,  830,
        867,  955,  973, 1060, 1087, 1166, 1191, 1264, 1352, 1353, 1364,
       1434, 1497])

In [41]:
np.cumsum(b,axis=1)

array([[ 91, 158, 256, 350],
       [ 94, 189, 270, 349],
       [ 50,  89, 131, 168],
       [ 88, 106, 193, 220],
       [ 79, 104, 177, 265],
       [  1,  12,  82, 145]])

In [42]:
# cummulative product
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [43]:
np.cumprod(a)

array([                  82,                 2460,               120540,
                    8558340,            847275660,           2541826980,
               177927888600,        1601350997400,      115297271812800,
           9223781745024000,   184475634900480000, -2950790742069231616,
        1518414728803155968,  1456458161104551936,  1948848082598494208,
        2083473504550780928,  8333894018203123712, -4583386878870290432,
        5036173111783849984,  5209189137264934912,  8701721528271634432,
        8391686448645931008,   224491699672449024, -8569109288121794560,
       -1563299715838115840])

#np.percentile
- numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [44]:
# percentile
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [45]:
np.max(a)

99

In [46]:
np.percentile(a,100)

99.0

In [47]:
np.percentile(a,50)

52.0

In [48]:
np.median(a)

52.0

#np.histogram
- Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [49]:
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [52]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 1, 2, 4, 2, 3, 1, 3, 4, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# Here the upper array tell us the number of element present in the given bin size

#np.corrcoef
- Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

# Correlation varies between -1 to 1.
- 1 correlation means the given two columns are highly correlated or directly proportional.
- -1 correlation means inversly propotional
- 0 means no correlation

In [55]:
salary = np.array([20000,40000,60000,80000])
experiance = np.array([2,3,4,5])

np.corrcoef(salary,experiance)

array([[1., 1.],
       [1., 1.]])

# np.isin
- With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [56]:
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [57]:
items = [10,20,30,40,50]
np.isin(a,items)

array([False,  True, False, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False])

In [59]:
# To get the values
a[np.isin(a,items)]

array([30, 20, 20, 30])

#np.flip
- The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [60]:
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [61]:
np.flip(a)

array([54, 44, 33, 90, 30, 34, 15, 57,  4, 20, 52, 86, 62, 84, 20, 80, 72,
        9, 70,  3, 99, 71, 49, 30, 82])

In [62]:
b

array([[91, 67, 98, 94],
       [94, 95, 81, 79],
       [50, 39, 42, 37],
       [88, 18, 87, 27],
       [79, 25, 73, 88],
       [ 1, 11, 70, 63]])

In [63]:
np.flip(b)

array([[63, 70, 11,  1],
       [88, 73, 25, 79],
       [27, 87, 18, 88],
       [37, 42, 39, 50],
       [79, 81, 95, 94],
       [94, 98, 67, 91]])

In [64]:
np.flip(b,axis = 0)

array([[ 1, 11, 70, 63],
       [79, 25, 73, 88],
       [88, 18, 87, 27],
       [50, 39, 42, 37],
       [94, 95, 81, 79],
       [91, 67, 98, 94]])

In [65]:
np.flip(b,axis = 1)

array([[94, 98, 67, 91],
       [79, 81, 95, 94],
       [37, 42, 39, 50],
       [27, 87, 18, 88],
       [88, 73, 25, 79],
       [63, 70, 11,  1]])

#np.put
- The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [66]:
a

array([82, 30, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [69]:
np.put(a,[0,1],[1,2])

In [72]:
a

array([ 1,  2, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

#np.delete
- The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [73]:
a

array([ 1,  2, 49, 71, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4,
       57, 15, 34, 30, 90, 33, 44, 54])

In [75]:
np.delete(a,[0,1,3])

# Here [0,1,3] these are the index numbers

array([49, 99,  3, 70,  9, 72, 80, 20, 84, 62, 86, 52, 20,  4, 57, 15, 34,
       30, 90, 33, 44, 54])

#Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [76]:
#union
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [77]:
# intersect
np.intersect1d(m,n)

array([3, 4, 5])

In [79]:
# It will give unique value
np.setdiff1d(m,n)

array([1, 2])

In [80]:
#np.setxor1d
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [81]:
#np.in1d
np.in1d(m,n)

array([False, False,  True,  True,  True])

In [82]:
m[np.in1d(m,n)]

array([3, 4, 5])

#np.clip
- numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [86]:
len(a)

25

In [85]:
# keep the values between 25-75
np.clip(a,a_min=25,a_max=75)

array([25, 25, 49, 71, 75, 25, 70, 25, 72, 75, 25, 75, 62, 75, 52, 25, 25,
       57, 25, 34, 30, 75, 33, 44, 54])

In [87]:
len(np.clip(a,a_min=25,a_max=75))

25

In [88]:
## 17. np.swapaxes

In [89]:
## 18. np.uniform

In [90]:
## 19. np.count_nonzero

In [91]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [92]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [93]:
# 25. np.allclose and equals