In [7]:
# Q: Write a Python Program to Add Two Matrices?
import numpy as np

def add_matrices(mat1, mat2):

    np_mat1 = np.array(mat1)
    np_mat2 = np.array(mat2)
    result = np_mat1 + np_mat2
    return result

matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]]

print("Matrix 1:\n")
print(np.array(matrix1))

print("\nMatrix 2:\n")
print(np.array(matrix2))

result_matrix = add_matrices(matrix1, matrix2)
print("\nResult of adding the two matrices:\n")
print(result_matrix)


Matrix 1:

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:

[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of adding the two matrices:

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [8]:
# Q: Write a Python Program to Multiply Two Matrices
import numpy as np

def multiply_matrices(mat1, mat2):

    np_mat1 = np.array(mat1)
    np_mat2 = np.array(mat2)
    result = np.dot(np_mat1, np_mat2)
    return result

matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]]

print("Matrix 1:")
print(np.array(matrix1))

print("\nMatrix 2:")
print(np.array(matrix2))

result_matrix = multiply_matrices(matrix1, matrix2)
print("\nResult of multiplying the two matrices:")
print(result_matrix)


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of multiplying the two matrices:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [9]:
# Q: Write a Python Program to Transpose a Matrix
import numpy as np

def transpose_matrix(mat):

    np_mat = np.array(mat)
    transposed_mat = np.transpose(np_mat)
    return transposed_mat

matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

print("Original Matrix:")
print(np.array(matrix))

transposed_matrix = transpose_matrix(matrix)
print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
# Q: Write a Python Program to Sort Words in Alphabetic Order
def sort_words_alphabetically(sentence):

    words = sentence.split()
    sorted_words = sorted(words)
    sorted_sentence = ' '.join(sorted_words)
    return sorted_sentence

sentence = "Python program to sort words in alphabetical order"
print("Original Sentence:", sentence)
print("Sentence with words sorted in alphabetical order:", sort_words_alphabetically(sentence))



Original Sentence: Python program to sort words in alphabetical order
Sentence with words sorted in alphabetical order: Python alphabetical in order program sort to words


In [13]:
# Q: Write a Python Program to Remove Punctuation From a String

import string

def remove_punctuation(sentence):


    translator = str.maketrans('', '', string.punctuation)

    cleaned_sentence = sentence.translate(translator)
    return cleaned_sentence

text = "Hello! How are you? I'm doing fine, thank you."
print("Original Text:", text)
print("Text with punctuation removed:", remove_punctuation(text))


Original Text: Hello! How are you? I'm doing fine, thank you.
Text with punctuation removed: Hello How are you Im doing fine thank you
